name: Build
on: [push]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["2.7", "3.9"]
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # --use-feature=in-tree-build
    - name: Test
      run: |
        pip --no-color --no-python-version-warning --disable-pip-version-check --no-cache-dir --no-input --verbose install dist/

    - name: After-Install Test
      shell: bash
      run: |
        echo $PATH
        ls -LR ~/.choosenim/toolchains/nim-#devel/
